### ISSUE TITLE
Clarify how to avoid collateral damage

### ISSUE THREAD

**Issue by mk-pmb** [bell07/minetest-woodcutting#9]
Hi! I'm trying to grow and chop trees near my tree house, so I'd love to have clear instructions in the readme about in which conditions it will be safe to use woodcutting to cut the non-house trees.

**Comment by bell07** [comment]
Added the hint 

> Works with all trees. The cutting just follow connected tree nodes in all directions for each cutted node and add them to the processing queue

to the README.

In addition with 

> You can add additional trees to process by digging other tree nodes manually
> The distance to the player is used to prefer next node so the player can partially influence the work direction on big areas

is all information given from my site.  To avoid the woodcutting from destroying your houses make sure the tree does not touch the houses (even edge-edge is  a connection) before starting the cutting.
Then go away from the house to the other site of the tree to be sure the tree is cutted from the not-house site.

As you see my English is not really useable for documentations. Feel free to propose the README part I can copy&paste., or just set up a pull request.

**Comment by mk-pmb** [comment]
Thanks! While the wording is technically precise, I guess this would be easier to understand for beginners:

```diff
-follow connected tree nodes in all 
+follow connected tree (trunk) blocks in all 
```

Also I tried this:

> You can add additional trees to process by digging other tree nodes manually

but when I dug the trunk with sneaking (as is required to activate woodcut), it seems to abort the previous woodcut. It seemed as if sometimes that abort would happen very shortly after I dug the trunk, thus also aborting the new woodcut.

When I do not sneak, the previous woodcut continues, but I get no visual feedback of whether the new tree was added.

**Comment by bell07** [comment]
Adjusted the both comments.
To add additional tree is without sneak key. There is no direct visual feedback, the neighbours of the digged node are just added to the woodcutting queue. The counter on the HUD output should be bigger, it is the queue size. 
Additional "feedback" is if you stay nearly the new tree, because the woodcutting process follow your player. You see the new tree will be processed.

**Comment by mk-pmb** [comment]
Thanks! The new readme is good, I like it. :-)
